#!/usr/bin/env python3
"""
Graph Neo4j Ingestion Script

Reads the manifest.json and CSV files generated by generate_data.py and loads them
into a Neo4j database using the official neo4j Python driver.

Usage:
    python ingest_data.py ./graph_data \
        --uri bolt://localhost:7687 \
        --user neo4j \
        --password <password> \
        [--database neo4j] \
        [--batch-size 500] \
        [--drop-existing]

Requirements:
    pip install neo4j
"""

import argparse
import csv
import json
import os
import sys
import time

try:
    from neo4j import GraphDatabase
except ImportError:
    print("ERROR: neo4j driver is not installed.")
    print("Install it with: pip install neo4j")
    print("Or if using the graph_venv: /home/claude/graph_venv/bin/pip install neo4j")
    sys.exit(1)


def read_csv(filepath):
    """Read a CSV file and return a list of dicts."""
    with open(filepath, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def chunks(lst, n):
    """Yield successive n-sized chunks from a list."""
    for i in range(0, len(lst), n):
        yield lst[i : i + n]


def create_constraints(session, manifest):
    """Create uniqueness constraints for each node label."""
    nodes = manifest.get("files", {}).get("nodes", {})
    for label, info in nodes.items():
        labels = info.get("labels", [label])
        for lbl in labels:
            query = (
                f"CREATE CONSTRAINT {lbl.lower()}_id IF NOT EXISTS "
                f"FOR (n:{lbl}) REQUIRE n._id IS UNIQUE"
            )
            try:
                session.run(query)
                print(f"   ✅ Constraint: {lbl}._id (unique)")
            except Exception as e:
                # Some older Neo4j versions have different syntax
                err = str(e)
                if "already exists" in err.lower():
                    print(f"   ⏭️  Constraint for {lbl}._id already exists")
                else:
                    print(f"   ⚠️  Constraint for {lbl}: {err}")
                    # Try older syntax
                    try:
                        query_old = (
                            f"CREATE CONSTRAINT ON (n:{lbl}) "
                            f"ASSERT n._id IS UNIQUE"
                        )
                        session.run(query_old)
                        print(f"   ✅ Constraint (legacy syntax): {lbl}._id")
                    except Exception:
                        print(f"   ❌ Could not create constraint for {lbl}")


def ingest_nodes(session, data_dir, manifest, batch_size):
    """Ingest node CSVs into Neo4j."""
    nodes = manifest.get("files", {}).get("nodes", {})
    total_created = 0

    for label, info in nodes.items():
        filepath = os.path.join(data_dir, info["file"])
        if not os.path.exists(filepath):
            print(f"   ⚠️  File not found: {filepath}, skipping {label}")
            continue

        rows = read_csv(filepath)
        labels_str = ":".join(info.get("labels", [label]))
        num_batches = (len(rows) + batch_size - 1) // batch_size
        created = 0

        print(f"\n   📦 {label} ({len(rows):,} nodes, {num_batches} batches)")

        for i, batch in enumerate(chunks(rows, batch_size)):
            query = f"UNWIND $rows AS row CREATE (n:{labels_str}) SET n = row"
            try:
                result = session.run(query, rows=batch)
                summary = result.consume()
                created += summary.counters.nodes_created
                print(f"      Batch {i + 1}/{num_batches}: {len(batch)} nodes", end="\r")
            except Exception as e:
                print(f"\n      ❌ Batch {i + 1} failed: {e}")

        print(f"      ✅ {created:,} {label} nodes created" + " " * 20)
        total_created += created

    return total_created


def ingest_relationships(session, data_dir, manifest, batch_size):
    """Ingest relationship CSVs into Neo4j."""
    rels = manifest.get("files", {}).get("relationships", {})
    total_created = 0

    for rel_type, info in rels.items():
        filepath = os.path.join(data_dir, info["file"])
        if not os.path.exists(filepath):
            print(f"   ⚠️  File not found: {filepath}, skipping {rel_type}")
            continue

        rows = read_csv(filepath)
        from_label = info["from_label"]
        to_label = info["to_label"]
        rel_props = info.get("properties", {})
        num_batches = (len(rows) + batch_size - 1) // batch_size
        created = 0

        print(f"\n   🔗 {from_label} -[{rel_type}]-> {to_label} ({len(rows):,} rels, {num_batches} batches)")

        # Build SET clause for relationship properties
        prop_keys = [k for k in rel_props.keys() if k not in ("_from_id", "_to_id")]
        if prop_keys:
            set_clause = ", ".join([f"r.{k} = row.{k}" for k in prop_keys])
            set_line = f"SET {set_clause}"
        else:
            set_line = ""

        for i, batch in enumerate(chunks(rows, batch_size)):
            query = (
                f"UNWIND $rows AS row "
                f"MATCH (a:{from_label} {{_id: row._from_id}}) "
                f"MATCH (b:{to_label} {{_id: row._to_id}}) "
                f"CREATE (a)-[r:{rel_type}]->(b) "
                f"{set_line}"
            )
            try:
                result = session.run(query, rows=batch)
                summary = result.consume()
                created += summary.counters.relationships_created
                print(f"      Batch {i + 1}/{num_batches}: {len(batch)} rels", end="\r")
            except Exception as e:
                print(f"\n      ❌ Batch {i + 1} failed: {e}")

        print(f"      ✅ {created:,} {rel_type} relationships created" + " " * 20)
        total_created += created

    return total_created


def verify(session):
    """Run verification queries and print results."""
    print("\n📋 Verification:")

    # Node counts
    result = session.run(
        "MATCH (n) RETURN labels(n)[0] AS label, count(n) AS count ORDER BY count DESC"
    )
    records = list(result)
    if records:
        print("   Nodes:")
        for r in records:
            print(f"      {r['label']}: {r['count']:,}")

    # Relationship counts
    result = session.run(
        "MATCH ()-[r]->() RETURN type(r) AS type, count(r) AS count ORDER BY count DESC"
    )
    records = list(result)
    if records:
        print("   Relationships:")
        for r in records:
            print(f"      {r['type']}: {r['count']:,}")


def clear_database(session):
    """Delete all nodes and relationships."""
    print("   🗑️  Clearing all data...")
    # Use batched delete for large databases
    while True:
        result = session.run(
            "MATCH (n) WITH n LIMIT 10000 DETACH DELETE n RETURN count(*) AS deleted"
        )
        record = result.single()
        deleted = record["deleted"] if record else 0
        if deleted == 0:
            break
        print(f"      Deleted {deleted:,} nodes...")
    print("   ✅ Database cleared")


def main():
    parser = argparse.ArgumentParser(
        description="Ingest generated graph data into Neo4j"
    )
    parser.add_argument(
        "data_dir", help="Directory containing manifest.json and CSV files"
    )
    parser.add_argument(
        "--uri",
        default="bolt://localhost:7687",
        help="Neo4j connection URI (default: bolt://localhost:7687)",
    )
    parser.add_argument("--user", default="neo4j", help="Neo4j username (default: neo4j)")
    parser.add_argument("--password", required=True, help="Neo4j password")
    parser.add_argument(
        "--database", default="neo4j", help="Neo4j database name (default: neo4j)"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=500,
        help="Rows per batch for UNWIND queries (default: 500)",
    )
    parser.add_argument(
        "--drop-existing",
        action="store_true",
        help="Clear all existing data before ingestion (use with caution!)",
    )

    args = parser.parse_args()

    # Load manifest
    manifest_path = os.path.join(args.data_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        print(f"❌ manifest.json not found in {args.data_dir}")
        print("   Run generate_data.py first to create the data and manifest.")
        sys.exit(1)

    with open(manifest_path, "r") as f:
        manifest = json.load(f)

    print(f"🚀 Neo4j Graph Ingestion")
    print(f"   URI:      {args.uri}")
    print(f"   Database: {args.database}")
    print(f"   Data dir: {os.path.abspath(args.data_dir)}")
    print(f"   Batch:    {args.batch_size} rows")
    print()

    # Connect
    try:
        driver = GraphDatabase.driver(args.uri, auth=(args.user, args.password))
        driver.verify_connectivity()
        print("   ✅ Connected to Neo4j")
    except Exception as e:
        print(f"   ❌ Connection failed: {e}")
        sys.exit(1)

    start_time = time.time()

    with driver.session(database=args.database) as session:
        # Optionally clear
        if args.drop_existing:
            clear_database(session)
            print()

        # Constraints
        print("🔒 Creating constraints...")
        create_constraints(session, manifest)

        # Nodes
        print("\n📥 Ingesting nodes...")
        total_nodes = ingest_nodes(session, args.data_dir, manifest, args.batch_size)

        # Relationships
        print("\n📥 Ingesting relationships...")
        total_rels = ingest_relationships(
            session, args.data_dir, manifest, args.batch_size
        )

        # Verify
        verify(session)

    driver.close()

    elapsed = time.time() - start_time
    print(f"\n🎉 Ingestion complete!")
    print(f"   {total_nodes:,} nodes, {total_rels:,} relationships")
    print(f"   Time: {elapsed:.1f}s")


if __name__ == "__main__":
    main()
