#!/usr/bin/env python3
"""
build_script.py — emit a standalone Faker-based generate.py from a run config.

Inputs:
  - A JSON config file (run_config.json) capturing what Claude and the user
    agreed on across the six conversational steps:
      - anchor_label, anchor_count
      - schema_path (arrows.app-format graph schema)
      - cardinality (per rel-type)
      - property_generators (per Label.property)
      - patterns (list of pattern specs)
      - output_dir, seed

Output:
  - A single self-contained generate.py file. It only needs `faker`. Run with:
        pip install faker
        python generate.py

The output script is intentionally readable so the user can edit it after
generation — change a generator, tweak a count, re-run. The config JSON is
embedded as a top-level constant so re-running with edits doesn't require
the original config file.

Usage:
    python build_script.py <config.json> <output.py>
"""

import argparse
import json
import sys
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# The generated script template.
#
# Triple-braced placeholders so str.format() doesn't fight with Python
# braces in the embedded code. We use {{...}} for actual code braces and
# {NAME} for substitution points. Only ONE substitution: {EMBEDDED_CONFIG}.
# Everything else is literal Python that runs against the embedded config.
# ─────────────────────────────────────────────────────────────────────────────

GENERATE_PY_TEMPLATE = '''#!/usr/bin/env python3
"""
generate.py — synthetic graph data, generated by graph-data-workflow.

Reads its config from the EMBEDDED_CONFIG constant below (originally written
by build_script.py). Edit the constant to tweak generators, cardinality, or
patterns, then re-run. Only dependency is `faker`.

    pip install faker
    python generate.py

Output:
    <output_dir>/nodes_<Label>.csv          one per node label
    <output_dir>/rels_<RelType>.csv         one per relationship type
    <output_dir>/injected_patterns.json     ground truth for planted patterns
    <output_dir>/schema.json                copy of the input schema
"""

import csv
import json
import math
import os
import random
import re
import sys
from collections import defaultdict
from datetime import datetime, timedelta

try:
    from faker import Faker
except ImportError:
    print("ERROR: faker is required. Install with: pip install faker", file=sys.stderr)
    sys.exit(1)


# ═══════════════════════════════════════════════════════════════════════════
# CONFIG — edit me to change the run, then re-execute.
# ═══════════════════════════════════════════════════════════════════════════

CONFIG = __EMBEDDED_CONFIG__


# ═══════════════════════════════════════════════════════════════════════════
# Generators
# ═══════════════════════════════════════════════════════════════════════════

fake = Faker()
Faker.seed(CONFIG.get("seed", 42))
random.seed(CONFIG.get("seed", 42))

_sequence_counters = defaultdict(int)


def _parse_relative_date(s):
    """Parse 'today', 'today-3y', 'today+30d' or an ISO date string."""
    if not isinstance(s, str):
        return s
    s = s.strip()
    if s == "today":
        return datetime.now()
    m = re.match(r"^today([+-])(\\d+)([dwmy])$", s)
    if m:
        sign, n, unit = m.group(1), int(m.group(2)), m.group(3)
        if sign == "-":
            n = -n
        if unit == "d":
            return datetime.now() + timedelta(days=n)
        if unit == "w":
            return datetime.now() + timedelta(weeks=n)
        if unit == "m":
            return datetime.now() + timedelta(days=30 * n)
        if unit == "y":
            return datetime.now() + timedelta(days=365 * n)
    return datetime.fromisoformat(s)


def make_generator(spec):
    """Return a zero-arg callable that produces values according to the spec.

    Supported types:
        faker        — calls fake.<method>(**args)
        categorical  — random.choices(values, weights)
        regex        — fake.bothify-style pattern via faker
        lognormal    — random.lognormvariate, optional min/max/round_to
        normal       — random.gauss, optional min/max/round_to
        uniform      — random.uniform or randint, optional round_to
        sequence     — counter with prefix/pad
        datetime     — random datetime in [start, end]
        derived      — value computed from another property; resolved later
        constant     — fixed value
    """
    t = spec.get("type")

    if t == "faker":
        method = spec["method"]
        args = spec.get("args", {})
        fn = getattr(fake, method)
        return lambda: fn(**args)

    if t == "categorical":
        values = spec["values"]
        weights = spec.get("weights")
        if weights:
            return lambda: random.choices(values, weights=weights, k=1)[0]
        return lambda: random.choice(values)

    if t == "regex":
        pattern = spec["pattern"]
        # Faker's hexify/bothify cover common cases. For full regex support
        # we'd need rstr or similar; here we handle the common patterns
        # used in our packs (alphanumeric ranges, fixed strings).
        return lambda: _regex_fill(pattern)

    if t == "lognormal":
        mu = spec.get("mu", 0.0)
        sigma = spec.get("sigma", 1.0)
        lo = spec.get("min")
        hi = spec.get("max")
        rd = spec.get("round_to")
        def _gen():
            v = random.lognormvariate(mu, sigma)
            if lo is not None: v = max(lo, v)
            if hi is not None: v = min(hi, v)
            if rd is not None: v = round(v, rd)
            return v
        return _gen

    if t == "normal":
        mean = spec.get("mean", 0.0)
        std = spec.get("std", 1.0)
        lo = spec.get("min")
        hi = spec.get("max")
        rd = spec.get("round_to")
        def _gen():
            v = random.gauss(mean, std)
            if lo is not None: v = max(lo, v)
            if hi is not None: v = min(hi, v)
            if rd is not None: v = round(v, rd)
            return v
        return _gen

    if t == "uniform":
        lo = spec["min"]
        hi = spec["max"]
        if spec.get("integer"):
            return lambda: random.randint(int(lo), int(hi))
        rd = spec.get("round_to")
        if rd is not None:
            return lambda: round(random.uniform(lo, hi), rd)
        return lambda: random.uniform(lo, hi)

    if t == "sequence":
        prefix = spec.get("prefix", "")
        start = spec.get("start", 1)
        pad = spec.get("pad_width")
        key = id(spec)
        _sequence_counters[key] = start - 1
        def _gen():
            _sequence_counters[key] += 1
            n = _sequence_counters[key]
            if pad:
                return f"{prefix}{n:0{pad}d}"
            return f"{prefix}{n}"
        return _gen

    if t == "datetime":
        start = _parse_relative_date(spec.get("start", "today-1y"))
        end = _parse_relative_date(spec.get("end", "today"))
        fmt = spec.get("format", "iso")
        def _gen():
            delta = (end - start).total_seconds()
            offset = random.uniform(0, delta)
            d = start + timedelta(seconds=offset)
            if fmt == "date":
                return d.date().isoformat()
            if fmt == "epoch_seconds":
                return int(d.timestamp())
            if fmt == "epoch_millis":
                return int(d.timestamp() * 1000)
            return d.isoformat()
        return _gen

    if t == "constant":
        return lambda: spec["value"]

    if t == "derived":
        # Marker — resolved during row construction (see _generate_node_row).
        return None

    # Unknown type — fall back to a safe word generator.
    return lambda: fake.word()


def _regex_fill(pattern):
    """Best-effort: handle [A-Z]{n}, [0-9]{n}, [A-F0-9]{n}, and literal text."""
    out = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "[":
            close = pattern.find("]", i)
            if close == -1:
                out.append(c); i += 1; continue
            charset = pattern[i+1:close]
            chars = _expand_charset(charset)
            i = close + 1
            # Check for {n}
            if i < len(pattern) and pattern[i] == "{":
                rclose = pattern.find("}", i)
                if rclose != -1:
                    n_str = pattern[i+1:rclose]
                    if "," in n_str:
                        lo, hi = n_str.split(",")
                        n = random.randint(int(lo), int(hi))
                    else:
                        n = int(n_str)
                    out.append("".join(random.choice(chars) for _ in range(n)))
                    i = rclose + 1
                    continue
            out.append(random.choice(chars))
        else:
            out.append(c); i += 1
    return "".join(out)


def _expand_charset(spec):
    chars = []
    i = 0
    while i < len(spec):
        if i + 2 < len(spec) and spec[i+1] == "-":
            for c in range(ord(spec[i]), ord(spec[i+2]) + 1):
                chars.append(chr(c))
            i += 3
        else:
            chars.append(spec[i]); i += 1
    return chars


def resolve_derived(label, prop_name, row, all_props):
    """Compute a derived property from already-generated row values."""
    spec = all_props.get(f"{label}.{prop_name}", {})
    src = spec.get("from", "")
    transform = spec.get("transform", "")
    src_label, _, src_prop = src.partition(".")
    src_val = row.get(src_prop, "") if src_label == label else ""
    if transform == "domain_from_email":
        return src_val.split("@", 1)[1] if "@" in src_val else ""
    if transform == "email_from_name":
        slug = re.sub(r"[^a-z]+", ".", str(src_val).lower()).strip(".")
        return f"{slug}@example.com"
    return src_val


# ═══════════════════════════════════════════════════════════════════════════
# Schema loading
# ═══════════════════════════════════════════════════════════════════════════

def load_schema(path):
    with open(path) as f:
        raw = json.load(f)
    if "initialGraph" in raw:
        return raw["initialGraph"]
    if "graph" in raw:
        return raw["graph"]
    return raw


def primary_label(node_def):
    labels = node_def.get("labels") or []
    return labels[0] if labels else node_def.get("caption", "Node")


# ═══════════════════════════════════════════════════════════════════════════
# Node count derivation
# ═══════════════════════════════════════════════════════════════════════════

def compute_node_counts(schema, anchor_label, anchor_count, cardinality):
    """Walk the cardinality table to compute counts for non-anchor labels.

    For each rel in cardinality, derive the size of the smaller side from
    the larger side and the avg fanout. Iterate to fixpoint so chains
    (Customer -> Account -> Transaction) propagate correctly.
    """
    counts = {primary_label(n): None for n in schema.get("nodes", [])}
    counts[anchor_label] = anchor_count

    # Lookup helper
    nodes_by_label = {primary_label(n): n for n in schema.get("nodes", [])}

    # Iterate up to N times to let chains propagate
    for _ in range(len(counts) + 5):
        progress = False
        for rel_type, card in cardinality.items():
            from_lbl = card["from"]
            to_lbl = card["to"]
            avg = card.get("avg", 1.0)
            kind = card.get("kind", "N:N")
            f = counts.get(from_lbl)
            t = counts.get(to_lbl)
            if f is not None and t is None:
                if kind in ("1:N", "N:N"):
                    counts[to_lbl] = max(1, int(round(f * avg)))
                    progress = True
                elif kind == "N:1":
                    counts[to_lbl] = max(1, int(round(f / max(avg, 1.0))))
                    progress = True
                elif kind == "1:1":
                    counts[to_lbl] = f
                    progress = True
            elif t is not None and f is None:
                if kind == "1:N":
                    counts[from_lbl] = max(1, int(round(t / max(avg, 1.0))))
                    progress = True
                elif kind == "N:1":
                    counts[from_lbl] = max(1, int(round(t * avg)))
                    progress = True
                elif kind == "1:1":
                    counts[from_lbl] = t
                    progress = True
        if not progress:
            break

    # Anything still None: default to anchor_count
    for k, v in list(counts.items()):
        if v is None:
            counts[k] = anchor_count

    return counts


# ═══════════════════════════════════════════════════════════════════════════
# Generation
# ═══════════════════════════════════════════════════════════════════════════

def generate_nodes(schema, counts, output_dir):
    """Generate one CSV per node label. Returns {label: [list of _id values]}.

    If multiple node defs in the schema share the same primary label
    (e.g. ["Account", "Internal"] and ["Account", "External"] both have
    primary label "Account"), they are treated as ONE logical label —
    the union of their properties is used and counts[label] rows are
    written once.
    """
    id_index = {}
    prop_gens = CONFIG.get("property_generators", {})

    # Group node defs by primary label and union their properties.
    grouped = {}  # label -> {prop_name: prop_type}
    for node_def in schema.get("nodes", []):
        label = primary_label(node_def)
        merged = grouped.setdefault(label, {})
        for p, t in node_def.get("properties", {}).items():
            # First-seen type wins; later defs are idempotent for matching props.
            merged.setdefault(p, t)

    for label, properties in grouped.items():
        n = counts.get(label, 0)
        prop_names = list(properties.keys())

        # Compile generators
        generators = {}
        for p in prop_names:
            full_key = f"{label}.{p}"
            if full_key in prop_gens:
                generators[p] = make_generator(prop_gens[full_key])
            else:
                generators[p] = _default_generator_for(p, properties[p])

        out_path = os.path.join(output_dir, f"nodes_{label}.csv")
        ids = []
        with open(out_path, "w", newline="") as fh:
            writer = csv.writer(fh)
            writer.writerow(["_id"] + prop_names)
            for i in range(n):
                row = {}
                # First pass: non-derived
                for p in prop_names:
                    spec = prop_gens.get(f"{label}.{p}", {})
                    if spec.get("type") == "derived":
                        continue
                    g = generators[p]
                    row[p] = g() if g is not None else ""
                # Second pass: derived
                for p in prop_names:
                    spec = prop_gens.get(f"{label}.{p}", {})
                    if spec.get("type") == "derived":
                        row[p] = resolve_derived(label, p, row, prop_gens)
                _id = f"{label.lower()}-{i}"
                ids.append(_id)
                writer.writerow([_id] + [row.get(p, "") for p in prop_names])

        id_index[label] = ids
        print(f"  wrote {out_path} ({n:,} rows)", file=sys.stderr)

    return id_index


def _default_generator_for(prop_name, prop_type):
    """Tiny fallback when a property has no generator in the config."""
    name = prop_name.lower()
    if "email" in name:
        return lambda: fake.email()
    if "phone" in name:
        return lambda: fake.phone_number()
    if "name" in name:
        return lambda: fake.name()
    if name in ("id", "uuid") or name.endswith("id"):
        return lambda: fake.uuid4()
    if "date" in name or "time" in name:
        return lambda: fake.date_time_this_decade().isoformat()
    if "amount" in name or "price" in name:
        return lambda: round(random.lognormvariate(4.0, 1.2), 2)

    pt = (prop_type or "string").lower()
    if pt in ("int", "integer", "long"):
        return lambda: random.randint(1, 10000)
    if pt in ("float", "double", "number"):
        return lambda: round(random.uniform(0.0, 1000.0), 2)
    if pt in ("boolean", "bool"):
        return lambda: random.choice([True, False])
    if pt in ("date",):
        return lambda: fake.date_this_decade().isoformat()
    if pt in ("datetime", "timestamp"):
        return lambda: fake.date_time_this_decade().isoformat()

    return lambda: fake.word()


def generate_rels(schema, id_index, output_dir):
    """Generate one CSV per relationship type. Returns {rel_type: count}.

    If multiple rel defs in the schema share the same rel-type but
    connect different label pairs (e.g. LOCATED_IN going Address→Country
    AND IP→Location), all such defs append to the same CSV. The header
    is written once on first encounter.
    """
    rel_counts = {}
    nodes_by_id = {n["id"]: n for n in schema.get("nodes", [])}
    rel_props = CONFIG.get("rel_property_generators", {})
    cardinality = CONFIG.get("cardinality", {})

    # Track which rel-type CSVs are already opened so we don't overwrite headers.
    opened = set()
    # Track the union of property names across all defs of a rel-type
    # so the header reflects every possible property column.
    union_props_per_rel = {}
    for rel_def in schema.get("relationships", []):
        u = union_props_per_rel.setdefault(rel_def["type"], {})
        for p, t in rel_def.get("properties", {}).items():
            u.setdefault(p, t)

    for rel_def in schema.get("relationships", []):
        rel_type = rel_def["type"]
        from_node = nodes_by_id[rel_def["fromId"]]
        to_node = nodes_by_id[rel_def["toId"]]
        from_lbl = primary_label(from_node)
        to_lbl = primary_label(to_node)

        from_ids = id_index.get(from_lbl, [])
        to_ids = id_index.get(to_lbl, [])
        if not from_ids or not to_ids:
            continue

        card = cardinality.get(rel_type, {"kind": "N:N", "avg": 1.0})
        kind = card.get("kind", "N:N")
        avg = card.get("avg", 1.0)

        # Use the UNION of properties for this rel-type as the header.
        all_prop_names = list(union_props_per_rel.get(rel_type, {}).keys())
        # Generators only for the props this particular def declares
        local_props = list(rel_def.get("properties", {}).keys())
        generators = {}
        for p in local_props:
            full_key = f"{rel_type}.{p}"
            if full_key in rel_props:
                generators[p] = make_generator(rel_props[full_key])
            else:
                generators[p] = _default_generator_for(p, rel_def["properties"][p])

        out_path = os.path.join(output_dir, f"rels_{rel_type}.csv")
        # Open in 'w' the first time this rel-type is seen; append after that.
        if rel_type not in opened:
            mode = "w"
            opened.add(rel_type)
            write_header = True
        else:
            mode = "a"
            write_header = False

        count = 0
        with open(out_path, mode, newline="") as fh:
            writer = csv.writer(fh)
            if write_header:
                writer.writerow(["_from_id", "_to_id"] + all_prop_names)

            def _row_for(fid, tid):
                vals = [fid, tid]
                for p in all_prop_names:
                    if p in generators:
                        vals.append(generators[p]())
                    else:
                        vals.append("")  # property not defined for this label pair
                return vals

            if kind == "1:1":
                for fid, tid in zip(from_ids, to_ids):
                    writer.writerow(_row_for(fid, tid))
                    count += 1
            elif kind == "1:N":
                for fid in from_ids:
                    n_targets = max(1, int(random.gauss(avg, max(avg * 0.3, 1))))
                    for _ in range(n_targets):
                        tid = random.choice(to_ids)
                        writer.writerow(_row_for(fid, tid))
                        count += 1
            elif kind == "N:1":
                for tid in to_ids:
                    n_sources = max(1, int(random.gauss(avg, max(avg * 0.3, 1))))
                    for _ in range(n_sources):
                        fid = random.choice(from_ids)
                        writer.writerow(_row_for(fid, tid))
                        count += 1
            else:  # N:N
                for fid in from_ids:
                    n_targets = max(1, int(random.gauss(avg, max(avg * 0.3, 1))))
                    for _ in range(n_targets):
                        tid = random.choice(to_ids)
                        if from_lbl == to_lbl and fid == tid:
                            continue  # skip accidental self-loops
                        writer.writerow(_row_for(fid, tid))
                        count += 1

        rel_counts[rel_type] = rel_counts.get(rel_type, 0) + count
        print(f"  wrote {out_path} (+{count:,} rows; total {rel_counts[rel_type]:,})", file=sys.stderr)

    return rel_counts


# ═══════════════════════════════════════════════════════════════════════════
# Pattern injection
# ═══════════════════════════════════════════════════════════════════════════

def inject_patterns(schema, id_index, output_dir):
    """Plant patterns and return the ground-truth manifest."""
    patterns = CONFIG.get("patterns", [])
    if not patterns:
        return None

    manifest = {"patterns": []}

    for pat in patterns:
        ptype = pat.get("type")
        if ptype == "cyclic":
            entries = _inject_cyclic(pat, schema, id_index, output_dir)
        elif ptype == "shared_attr":
            entries = _inject_shared_attr(pat, schema, id_index, output_dir)
        elif ptype == "hub":
            entries = _inject_hub(pat, schema, id_index, output_dir)
        else:
            print(f"  WARN: unknown pattern type {ptype!r}, skipping", file=sys.stderr)
            continue
        manifest["patterns"].append({"type": ptype, "spec": pat, "instances": entries})
        print(f"  planted {len(entries)} {ptype} patterns", file=sys.stderr)

    out_path = os.path.join(output_dir, "injected_patterns.json")
    with open(out_path, "w") as fh:
        json.dump(manifest, fh, indent=2)
    return out_path


def _append_rel_rows(output_dir, rel_type, rows):
    out_path = os.path.join(output_dir, f"rels_{rel_type}.csv")
    file_exists = os.path.exists(out_path)
    with open(out_path, "a", newline="") as fh:
        writer = csv.writer(fh)
        if not file_exists:
            writer.writerow(["_from_id", "_to_id"])
        for r in rows:
            writer.writerow(r)


def _inject_cyclic(pat, schema, id_index, output_dir):
    """A→B→C→...→A rings on a single node label via a self-rel."""
    rel_type = pat.get("rel")
    node_label = pat.get("node")
    count = pat.get("count", 50)
    rs = pat.get("ring_size", [3, 5])
    ids = id_index.get(node_label, [])
    if len(ids) < max(rs):
        return []

    instances = []
    appended = []
    for _ in range(count):
        size = random.randint(rs[0], rs[1])
        ring = random.sample(ids, size)
        for i in range(size):
            appended.append([ring[i], ring[(i + 1) % size]])
        instances.append({"ring": ring})
    _append_rel_rows(output_dir, rel_type, appended)
    return instances


def _inject_shared_attr(pat, schema, id_index, output_dir):
    """N members all linked to one shared hub (e.g. shared device cluster)."""
    rel_type = pat.get("rel")
    hub_label = pat.get("hub")
    member_label = pat.get("member")
    count = pat.get("count", 100)
    cs = pat.get("cluster_size", [5, 10])
    hub_ids = id_index.get(hub_label, [])
    member_ids = id_index.get(member_label, [])
    if not hub_ids or not member_ids:
        return []

    instances = []
    appended = []
    for _ in range(count):
        size = random.randint(cs[0], cs[1])
        if len(member_ids) < size:
            continue
        hub = random.choice(hub_ids)
        members = random.sample(member_ids, size)
        for m in members:
            appended.append([hub, m])
        instances.append({"hub": hub, "members": members})
    _append_rel_rows(output_dir, rel_type, appended)
    return instances


def _inject_hub(pat, schema, id_index, output_dir):
    """A few nodes with abnormally high out-degree."""
    rel_type = pat.get("rel")
    count = pat.get("count", 5)
    fanout = pat.get("fanout", 200)
    schema_rels = {r["type"]: r for r in schema.get("relationships", [])}
    if rel_type not in schema_rels:
        return []
    nodes_by_id = {n["id"]: n for n in schema.get("nodes", [])}
    rel_def = schema_rels[rel_type]
    from_lbl = primary_label(nodes_by_id[rel_def["fromId"]])
    to_lbl = primary_label(nodes_by_id[rel_def["toId"]])
    from_ids = id_index.get(from_lbl, [])
    to_ids = id_index.get(to_lbl, [])
    if not from_ids or not to_ids:
        return []

    instances = []
    appended = []
    for _ in range(count):
        hub = random.choice(from_ids)
        targets = random.sample(to_ids, min(fanout, len(to_ids)))
        for t in targets:
            appended.append([hub, t])
        instances.append({"hub": hub, "fanout": len(targets)})
    _append_rel_rows(output_dir, rel_type, appended)
    return instances


# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════

def main():
    output_dir = CONFIG.get("output_dir", "./graph_data")
    os.makedirs(output_dir, exist_ok=True)

    schema = load_schema(CONFIG["schema_path"])

    # Persist schema next to the CSVs so downstream tools have a single source.
    with open(os.path.join(output_dir, "schema.json"), "w") as fh:
        json.dump({"graph": schema}, fh, indent=2)

    print(f"Generating into {output_dir}", file=sys.stderr)

    counts = compute_node_counts(
        schema,
        CONFIG["anchor_label"],
        CONFIG["anchor_count"],
        CONFIG.get("cardinality", {}),
    )
    print(f"Node counts: {counts}", file=sys.stderr)

    id_index = generate_nodes(schema, counts, output_dir)
    rel_counts = generate_rels(schema, id_index, output_dir)
    inject_patterns(schema, id_index, output_dir)

    print(file=sys.stderr)
    print("Done.", file=sys.stderr)
    total_nodes = sum(counts.values())
    total_rels = sum(rel_counts.values())
    print(f"  Total: {total_nodes:,} nodes, {total_rels:,} relationships", file=sys.stderr)


if __name__ == "__main__":
    main()
'''


# ─────────────────────────────────────────────────────────────────────────────
# Templater entry point
# ─────────────────────────────────────────────────────────────────────────────

def build_script(config_path, output_path):
    """Read config, embed it as a literal Python dict, write the runnable script."""
    with open(config_path) as f:
        config = json.load(f)

    # Embed the config as a Python literal. json.dumps then a simple
    # bool/null fix-up is more robust than building a repr of nested dicts.
    config_repr = json.dumps(config, indent=4)
    # Convert JSON literals to Python literals
    config_repr = (config_repr
        .replace(": true", ": True")
        .replace(": false", ": False")
        .replace(": null", ": None"))

    # Simple string replacement (not str.format) so that braces inside the
    # template — used by f-strings, dict literals, etc. — pass through
    # untouched. We use a sentinel that can't appear in legitimate Python.
    rendered = GENERATE_PY_TEMPLATE.replace("__EMBEDDED_CONFIG__", config_repr)

    with open(output_path, "w") as f:
        f.write(rendered)
    os.chmod(output_path, 0o755)


def main():
    ap = argparse.ArgumentParser(
        description="Emit a standalone generate.py from a run config.",
    )
    ap.add_argument("config", help="Path to run_config.json")
    ap.add_argument("output", help="Path where generate.py should be written")
    args = ap.parse_args()

    build_script(args.config, args.output)
    print(f"Wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    import os
    main()
